language: go

go_import_path: github.ibm.com/IBMPrivateCloud/icp-management-ingress

go:
  - 1.8

os:
  - power
  - linux

# Only build on master, stable branches and tag
# The stable branch and tag should be leading with numbers
branches:
  only:
    - master
    - /^[0-9]+\..*$/

before_install:
  - source travis-env.sh

install:
  - sudo apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
  - echo "deb https://apt.dockerproject.org/repo ubuntu-precise main" | sudo tee /etc/apt/sources.list.d/docker.list
  - sudo apt-get update
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      sudo apt-get install -y docker-engine;
      sudo chown ${USER} /var/run/docker.sock;
    fi

before_script:
  - make lint
  - make docker-login

script:
  - make test
  - make image

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" && make release || echo "success"
