language: go
go:
  - "1.13.x"

services:
  - docker

branches:
  only:
    - master
    - /^release-[0-9]+\..*$/

addons:
  sonarcloud:
    organization: "open-cluster-management"
    token:
      secure: "YfBu5HaTQCnvYXc9K5kkgCE+bpgjUPoV8jbI8/FoapBOZk8VbSkSArtgRZiv2TjgAKtU/vh2PqTfffpudjKMdr2oFloYQdWIcMMxBz1PFARUGQgxGjFhG8vTQEQh2cEfpqhmbi7uFfgQPFRpsuz3R5ZJelDPSj3a+OSVOjlu3EapRZrQRdOCCqd1XPCLGZPn/OrdnRQI3ILBohGfH4bU+e1tUUZelDH3ZKqlEQARxwQ2ZWXdTrVRAuHHrd+H1zqdAVILZBuJ2W5o5BOVyUNkcERWNhX/UiN8Xamcs4pzR7DgUuUTQccnet9rn78jGv73bLnMIyh5RNbN56kHqPl8czEnANshMRwTd2byqF1PwH/npify1bxGxdZeW/VtqiZtmITreEcRf5FJIiaiMHskwGLsmodOd0axnpekOJN57NBY6JlcOEUYQcr1ViCdNkL3+9KEHi6+XzQSr5ZeoY3JoR22jtqD3SUBf0nMw7qx/GRBj+tJ7hPLXjx9ZMf8tZ4TFgswlR37j0by0ZQO8PAkUhHepUa5n3Q515Q3jgIJB1jz09ZZJDhaL+1PcnCsweAa+sVzT1AqSIkv/Tg59ydE4g3nItVsSAWlrnU5EKLPGqZyZlHvmPI5wfxEsSUE2TnB+9TxwqnXR09iXe2M8Q53y7zAV3L1IzMjJD0ln7DDgFk="
env:
  global:
    # Required
    - OS=linux
    - COMPONENT_TAG_EXTENSION="-${TRAVIS_COMMIT}"
    # Component Specific
    - COMPONENT_INIT_COMMAND=${TRAVIS_BUILD_DIR}/build/install-dependencies.sh
    - COMPONENT_BUILD_COMMAND=${TRAVIS_BUILD_DIR}/build/build.sh
    - COMPONENT_UNIT_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-unit-tests.sh
    - COMPONENT_E2E_TEST_COMMAND=${TRAVIS_BUILD_DIR}/build/run-e2e-tests.sh


stages:
  - build
  - unit-test
  - test-e2e
  - release-ff
  - publish

before_script:
  - make init

jobs:
  include:
    - stage: build
      name: "Build the image and push"
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/build
        - make component/push
        - if [ "$IMAGE_SCAN" != "false" ]; then make security/scans; fi;
    - stage: unit-test
      name: "Build and run unit tests"
      script:
        - make component/test/unit
        - make sonar/go
        - make copyright-check TRAVIS_BRANCH=${TRAVIS_BRANCH}
    - stage: test-e2e
      name: "Run e2e tests"
      if: type = pull_request
      script:
        - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then export COMPONENT_TAG_EXTENSION="-PR${TRAVIS_PULL_REQUEST}-${TRAVIS_COMMIT}"; fi;
        - make component/pull
        - make component/test/e2e
    - stage: release-ff
      name: "Push commits to current release branch"
      if: type = push AND branch =~ /^master$/
      script:
        - make component/build
        - make release-ff
    - stage: publish
      name: "Publish the image to quay with an official version/sha tag and publish entry to integration pipeline stage"
      if: type = push AND branch =~ /^release-[0-9]+\..*$/
      script:
        - make pipeline-manifest/update PIPELINE_MANIFEST_COMPONENT_SHA256=${TRAVIS_COMMIT} PIPELINE_MANIFEST_COMPONENT_REPO=${TRAVIS_REPO_SLUG} PIPELINE_MANIFEST_BRANCH=${TRAVIS_BRANCH}
