language: go

go_import_path: github.ibm.com/IBMPrivateCloud/icp-management-ingress

go:
  - 1.8

os:
  - linux
  - linux-ppc64le

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
  - make lint
  - make docker-login

script:
  - make image

after_success:
  - test "$TRAVIS_PULL_REQUEST" = "false" && make release || echo "success"
