language: go

go_import_path: github.ibm.com/IBMPrivateCloud/icp-management-ingress

go:
  - "1.10"

os:
  - linux
  - linux-ppc64le
  - linux-s390

services:
  - docker

branches:
  only:
    - master
    - /^[0-9]+\..*$/
    - /^v[0-9]+\..*$/
    - /^release-[0-9]+\..*$/

before_install:
  - source travis-env.sh

install:
  - docker info

before_script:
#  - make deps lint
  - make docker-login

script:
#  - make fmt test coverage openresty image
  - make fmt openresty image

after_success:
  - test "$TRAVIS_EVENT_TYPE" != "pull_request" && make release || echo "success"
