---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: catalog-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/auth-type: "id-token"
spec:
  rules:
    - http:
        paths:
          - path: /catalog/
            backend:
              serviceName: catalog-ui
              servicePort: 4000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helm-api
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/rewrite-target: "/"
spec:
  rules:
    - http:
        paths:
          - path: /helm-api/
            backend:
              serviceName: helm-api
              servicePort: 3000

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: helm-repo
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/rewrite-target: "/"
spec:
  rules:
    - http:
        paths:
          - path: /helm-repo/
            backend:
              serviceName: helmrepo
              servicePort: 3001
