apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: metering-ui
  namespace: kube-system
  annotations:
    kubernetes.io/ingress.class: "ibm-icp-management"
    icp.management.ibm.com/auth-type: "id-token"
spec:
  rules:
  - http:
      paths:
      - path: /metering/
        backend:
          serviceName: metering-ui
          servicePort: 3130
